
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Estudo2;

public class App {
 
    public static void main(String[] args) {
        
        int mar = 10+10;
        System.out.println(mar);
        
        mar = 30;
        System.out.println(mar);
        
        final int han = 10;
        System.out.println(han);
        
        
        float combustivel = 5.79f;
        int litroPorKm = 12;
        int distKMviagem = 1580;
        
        int litrosconsumidos = distKMviagem/litroPorKm;
        
        float GastoTotal = litrosconsumidos*combustivel;
        
        System.out.println("total gasto é =" + GastoTotal);
        
                
        
        // boolean = verdairo ou falso
        
        boolean hanna;              // boolean é para false e true 
        
        
        
        
        // estruturas condicionais é para achar um verdadeiro ou falso
        
        int numero = 11 ;
        
        
        boolean par = (numero % 2) == 0;   //resto
       
        if(par){
            System.out.println("numeto par");
        }else
             System.out.println("numero impar");
        
        
        if(par){
            System.out.println("numeto par");
       
         }
        
        if(!par){
            System.out.println("numeto impar");
        
        }
        
        
        
        //estrutura condicionais ex 2
    
      final float precoEtanol = 5.79f;
      final float precoGasolina = 6.66f;
      final int kmLitro = 11;
      final int  kmViagem = 1580;
      String tipoCombustivel = "Gasolina";
      float totalGasto;                       //variavel de fora
      
      final int kmLitroCarro = kmViagem/kmLitro;
      
      if (tipoCombustivel == "Gasolina"){
       totalGasto = kmLitroCarro * precoGasolina;
      }else{
       totalGasto = kmLitroCarro * precoEtanol;
      }
        System.out.println(totalGasto);       //valor de fora
        
        
       //OUTRO JEITO
       
       final float precoEtanol1 = 5.79f;
      final float precoGasolina1 = 6.66f;
      final int kmLitro1 = 11;
      final int  kmViagem1 = 1580;
      String tipoCombustivel1 = "Gasolina";
      
      
      final int kmLitroCarro1 = kmViagem1/kmLitro1;
      
      if (tipoCombustivel1 == "Gasolina"){
      final float totalGasto1 = kmLitroCarro1 * precoGasolina1;  //variavel dentro
      System.out.println(totalGasto); 
      }else{
       final float totalGasto1 = kmLitroCarro1 * precoEtanol1;  //variavel dentro
      System.out.println(totalGasto); 
      }
              //valor de fora
        
        
final float nota1 = 5;
final float nota2 = 2;
final float nota3 = 0;


final float media = (nota1 + nota2 + nota3) / 3;

if(media < 5){
    System.out.println("reprovado");
}else if(media >= 5 && media <= 7){
    System.out.println("recuperação");
}else{
    System.out.println("Passou de ano");
}


//ex 3

final float altura = 1.60f;
final float peso = 50;
                                   //potencia
final float imc = (float) (peso /Math.pow(altura, 2));        // esse meth.pow é o mesmo que altura*altura  muda a quantidade nesse numero 2// 

if(imc < 18.5){
    System.out.println("Abaixo do peso");
}else if(imc >= 18.5 && imc < 25){
    System.out.println("peso normal");
}else if (imc >= 25 && imc < 30){
    System.out.println("acima do peso");
}else if (imc >= 30 && imc < 40){
    System.out.println("obeso");
}else{
   System.out.println("obesidade grave");
}



 }
}
  