/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author ACER
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Tollbar = new javax.swing.JPanel();
        jLabel1ToobarTitle = new javax.swing.JLabel();
        jLabel2ToolBarSubtitle = new javax.swing.JLabel();
        jPanel2Projects = new javax.swing.JPanel();
        jLabel3ProjetcstTitle = new javax.swing.JLabel();
        jLabel5ProjectsAdd = new javax.swing.JLabel();
        jPanel3Tasks = new javax.swing.JPanel();
        jLabel4TasksTitle = new javax.swing.JLabel();
        jLabel6TasksAdd = new javax.swing.JLabel();
        jPanel4ProjectsList = new javax.swing.JPanel();
        jScrollPane1Projects = new javax.swing.JScrollPane();
        jList1Projects = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6EmptyList = new javax.swing.JPanel();
        jLabel7EmptyListIcon = new javax.swing.JLabel();
        jLabel8EmptyListTitle = new javax.swing.JLabel();
        jLabel9EmptyListSubTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1Tollbar.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1Tollbar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1ToobarTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1ToobarTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1ToobarTitle.setIcon(new javax.swing.ImageIcon("C:\\Profissão\\Meusprojetos\\aulaJavaScript\\JAVASCRIPT---DIO\\JAVA-START CAPGEMINI\\TodoApp\\src\\main\\img\\tick.png")); // NOI18N
        jLabel1ToobarTitle.setText("TodoApp");

        jLabel2ToolBarSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2ToolBarSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2ToolBarSubtitle.setText("Não deixe de anotar nada.");

        javax.swing.GroupLayout jPanel1TollbarLayout = new javax.swing.GroupLayout(jPanel1Tollbar);
        jPanel1Tollbar.setLayout(jPanel1TollbarLayout);
        jPanel1TollbarLayout.setHorizontalGroup(
            jPanel1TollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1TollbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1TollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1ToobarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .addComponent(jLabel2ToolBarSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1TollbarLayout.setVerticalGroup(
            jPanel1TollbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1TollbarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1ToobarTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel2ToolBarSubtitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Projects.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2Projects.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3ProjetcstTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3ProjetcstTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3ProjetcstTitle.setText("Projetos");

        jLabel5ProjectsAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5ProjectsAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5ProjectsAdd.setIcon(new javax.swing.ImageIcon("C:\\Profissão\\Meusprojetos\\aulaJavaScript\\JAVASCRIPT---DIO\\JAVA-START CAPGEMINI\\TodoApp\\src\\main\\img\\add.png")); // NOI18N

        javax.swing.GroupLayout jPanel2ProjectsLayout = new javax.swing.GroupLayout(jPanel2Projects);
        jPanel2Projects.setLayout(jPanel2ProjectsLayout);
        jPanel2ProjectsLayout.setHorizontalGroup(
            jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3ProjetcstTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5ProjectsAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2ProjectsLayout.setVerticalGroup(
            jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5ProjectsAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3ProjetcstTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Tasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3Tasks.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4TasksTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4TasksTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4TasksTitle.setText("Tarefas");

        jLabel6TasksAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6TasksAdd.setIcon(new javax.swing.ImageIcon("C:\\Profissão\\Meusprojetos\\aulaJavaScript\\JAVASCRIPT---DIO\\JAVA-START CAPGEMINI\\TodoApp\\src\\main\\img\\add.png")); // NOI18N

        javax.swing.GroupLayout jPanel3TasksLayout = new javax.swing.GroupLayout(jPanel3Tasks);
        jPanel3Tasks.setLayout(jPanel3TasksLayout);
        jPanel3TasksLayout.setHorizontalGroup(
            jPanel3TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3TasksLayout.createSequentialGroup()
                .addComponent(jLabel4TasksTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6TasksAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel3TasksLayout.setVerticalGroup(
            jPanel3TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3TasksLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6TasksAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel3TasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4TasksTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4ProjectsList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4ProjectsList.setForeground(new java.awt.Color(255, 255, 255));

        jList1Projects.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jList1Projects.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1Projects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1Projects.setFixedCellHeight(50);
        jList1Projects.setSelectionBackground(new java.awt.Color(0, 153, 102));
        jScrollPane1Projects.setViewportView(jList1Projects);

        javax.swing.GroupLayout jPanel4ProjectsListLayout = new javax.swing.GroupLayout(jPanel4ProjectsList);
        jPanel4ProjectsList.setLayout(jPanel4ProjectsListLayout);
        jPanel4ProjectsListLayout.setHorizontalGroup(
            jPanel4ProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4ProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1Projects)
                .addContainerGap())
        );
        jPanel4ProjectsListLayout.setVerticalGroup(
            jPanel4ProjectsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4ProjectsListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1Projects, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jPanel6EmptyList.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7EmptyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7EmptyListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/lists.png"))); // NOI18N

        jLabel8EmptyListTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8EmptyListTitle.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8EmptyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8EmptyListTitle.setText("Nenhuma tarefa por aqui.");

        jLabel9EmptyListSubTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9EmptyListSubTitle.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9EmptyListSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9EmptyListSubTitle.setText("Clique no botao mmais para adicionar uma nova tarefa.");

        javax.swing.GroupLayout jPanel6EmptyListLayout = new javax.swing.GroupLayout(jPanel6EmptyList);
        jPanel6EmptyList.setLayout(jPanel6EmptyListLayout);
        jPanel6EmptyListLayout.setHorizontalGroup(
            jPanel6EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7EmptyListIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8EmptyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9EmptyListSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6EmptyListLayout.setVerticalGroup(
            jPanel6EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6EmptyListLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel7EmptyListIcon)
                .addGap(18, 18, 18)
                .addComponent(jLabel8EmptyListTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabel9EmptyListSubTitle)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6EmptyList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6EmptyList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1Tollbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2Projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4ProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3Tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1Tollbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2Projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3Tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4ProjectsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1ToobarTitle;
    private javax.swing.JLabel jLabel2ToolBarSubtitle;
    private javax.swing.JLabel jLabel3ProjetcstTitle;
    private javax.swing.JLabel jLabel4TasksTitle;
    private javax.swing.JLabel jLabel5ProjectsAdd;
    private javax.swing.JLabel jLabel6TasksAdd;
    private javax.swing.JLabel jLabel7EmptyListIcon;
    private javax.swing.JLabel jLabel8EmptyListTitle;
    private javax.swing.JLabel jLabel9EmptyListSubTitle;
    private javax.swing.JList<String> jList1Projects;
    private javax.swing.JPanel jPanel1Tollbar;
    private javax.swing.JPanel jPanel2Projects;
    private javax.swing.JPanel jPanel3Tasks;
    private javax.swing.JPanel jPanel4ProjectsList;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6EmptyList;
    private javax.swing.JScrollPane jScrollPane1Projects;
    // End of variables declaration//GEN-END:variables
}
